services:
  - type: web
    name: rag-chatapp-backend
    env: docker
    dockerContext: backend
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
